-- Generated from data/prompts.ts. Converts static examples into real image posts owned by seed creators.
drop trigger if exists image_posts_authenticated_rate_limit on public.image_posts;

with seed_creators(id, email, auth_nickname, nickname, bio, specialty) as (
  values
    ('10000000-0000-4000-8000-000000000001'::uuid, 'seed-retro@promptlab.example', 'seed_retro', '레트로사진관', '폰카, 필름, 생활 스냅 계열의 실험 프롬프트를 모아두는 크리에이터.', '폰카, 필름, 아날로그 스냅, 시네마틱 사진'),
    ('10000000-0000-4000-8000-000000000002'::uuid, 'seed-product@promptlab.example', 'seed_product', '제품컷스튜디오', '광고컷, 상세페이지, 무브랜드 제품사진 프롬프트를 정리합니다.', '제품사진, 광고컷, 스킨케어, 럭셔리 스틸라이프'),
    ('10000000-0000-4000-8000-000000000003'::uuid, 'seed-character@promptlab.example', 'seed_character', '캐릭터공방', '게임, 웹툰, 키비주얼에 쓰기 좋은 캐릭터 제작 프롬프트를 실험합니다.', '캐릭터, 게임 UI, 웹툰 표지, 키비주얼'),
    ('10000000-0000-4000-8000-000000000004'::uuid, 'seed-space@promptlab.example', 'seed_space', '공간설계자', '3D 공간, 배경 컨셉트, 월드빌딩용 이미지 프롬프트를 다룹니다.', '3D, 배경, 공간설계, 월드빌딩'),
    ('10000000-0000-4000-8000-000000000005'::uuid, 'seed-edit@promptlab.example', 'seed_edit', '편집실험실', '콜라주, 콘셉트시트, 스티커룩처럼 편집감 있는 프롬프트를 올립니다.', '이미지 편집, 콜라주, Y2K, 콘셉트시트'),
    ('10000000-0000-4000-8000-000000000006'::uuid, 'seed-horror@promptlab.example', 'seed_horror', '호러아카이브', '아날로그 호러, 리미널 공간, VHS 질감의 이미지 프롬프트를 모아둡니다.', '아날로그 호러, VHS, 리미널, 폰카 공포')
)
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at
)
select
  '00000000-0000-0000-0000-000000000000'::uuid,
  id,
  'authenticated',
  'authenticated',
  email,
  null,
  now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('nickname', auth_nickname),
  now(),
  now()
from seed_creators
on conflict (id) do update
set raw_user_meta_data = excluded.raw_user_meta_data, updated_at = now();

with seed_creators(id, nickname, bio, specialty) as (
  values
    ('10000000-0000-4000-8000-000000000001'::uuid, '레트로사진관', '폰카, 필름, 생활 스냅 계열의 실험 프롬프트를 모아두는 크리에이터.', '폰카, 필름, 아날로그 스냅, 시네마틱 사진'),
    ('10000000-0000-4000-8000-000000000002'::uuid, '제품컷스튜디오', '광고컷, 상세페이지, 무브랜드 제품사진 프롬프트를 정리합니다.', '제품사진, 광고컷, 스킨케어, 럭셔리 스틸라이프'),
    ('10000000-0000-4000-8000-000000000003'::uuid, '캐릭터공방', '게임, 웹툰, 키비주얼에 쓰기 좋은 캐릭터 제작 프롬프트를 실험합니다.', '캐릭터, 게임 UI, 웹툰 표지, 키비주얼'),
    ('10000000-0000-4000-8000-000000000004'::uuid, '공간설계자', '3D 공간, 배경 컨셉트, 월드빌딩용 이미지 프롬프트를 다룹니다.', '3D, 배경, 공간설계, 월드빌딩'),
    ('10000000-0000-4000-8000-000000000005'::uuid, '편집실험실', '콜라주, 콘셉트시트, 스티커룩처럼 편집감 있는 프롬프트를 올립니다.', '이미지 편집, 콜라주, Y2K, 콘셉트시트'),
    ('10000000-0000-4000-8000-000000000006'::uuid, '호러아카이브', '아날로그 호러, 리미널 공간, VHS 질감의 이미지 프롬프트를 모아둡니다.', '아날로그 호러, VHS, 리미널, 폰카 공포')
)
insert into public.profiles (id, nickname, bio, specialty, website_url, instagram_url, x_url, role)
select id, nickname, bio, specialty, '', '', '', 'user'::public.user_role
from seed_creators
on conflict (id) do update
set
  nickname = excluded.nickname,
  bio = excluded.bio,
  specialty = excluded.specialty,
  updated_at = now();

with seed_posts(id, version_id, author_id, title, description, category, model, aspect_ratio, style, image_url, tags, prompt_body, prompt_language, offset_hours) as (
  values
    ('d4c9ddec-369b-49fd-864e-7f3bce35f3ae'::uuid, 'b2dfeb06-bd49-40f1-882a-6204feb6d206'::uuid, '10000000-0000-4000-8000-000000000004'::uuid, 'QR 코드가 숨어 있는 건축 렌더', 'ControlNet tile_resample로 QR 코드를 고급 주택 렌더 안에 숨긴 인기 워크플로우.', '3D/공간', 'GPT Image 2.0', '1:1', 'Hidden QR / Architecture', 'https://i.redd.it/8j3vz9j0vj4b1.png', array['QR', 'ControlNet', '건축', '워크플로우']::text[], 'A photo-realistic rendering of a 2 story house with greenery, pool, (Botanical:1.5), (Photorealistic:1.3), (Highly detailed:1.2), (Natural light:1.2), art inspired by Architectural Digest, Vogue Living, and Elle Decor, <lora:epiNoiseoffset_v2:1>

Negative prompt: bad_pictures, (bad_prompt_version2:0.8), EasyNegative, 3d, cartoon, anime, sketches, (worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale))

Workflow notes: img2img with QR code image, denoising strength 1, ControlNet tile_resample, model control_v11f1e_sd15_tile, control weight 0.9, pixel perfect true.', 'mixed'::public.prompt_language, 1),
    ('76eab710-47c7-49c1-89b9-fcedcd55d8f3'::uuid, 'fc2b1e89-fa4d-49e7-8214-9be4804eccbb'::uuid, '10000000-0000-4000-8000-000000000001'::uuid, '바이킹 롱하우스 시대 셀피', '역사 속 인물들이 전면 카메라 셀피를 찍는다는 설정의 Midjourney 프롬프트.', '사진/시네마틱', 'GPT Image 2.0', '3:2', 'Historical Selfie', 'https://preview.redd.it/hj9f60entqoa1.png?width=1344&format=png&auto=webp&s=825bb4788696f05720a8d21787e4a02b56dacb22', array['셀피', '역사', '바이킹', '포토리얼']::text[], 'A group of male Norse, Dane, and Vikings huddled together and is taking a group selfie picture together in 793 CE. They are drinking ale at a feast in a Viking longhouse. They are all wearing traditional Viking armor and helmets. Everyone smiling directly at the camera. The image is photorealistic, has natural lighting, and is taken with a front-facing phone selfie camera by one of the Vikings. --ar 3:2 --s 1000 --no phone --v 5 --q 2', 'mixed'::public.prompt_language, 2),
    ('16b84351-c403-4ed4-82b9-e69bded18603'::uuid, '27bb1272-c36b-463b-8b19-518fb6025305'::uuid, '10000000-0000-4000-8000-000000000001'::uuid, '2000년대 폰카처럼 일부러 못 찍은 사진', 'AI 이미지가 너무 완벽해 보이는 문제를 거꾸로 이용해 저품질 폰카 질감을 만들려는 실험형 프롬프트.', '사진/시네마틱', 'GPT Image 2.0', '9:16', '2000s Phone Camera', 'https://i.imgur.com/sC6szZBh.jpg', array['폰카', '저화질', '리얼리즘', 'SDXL']::text[], '(candid poorly lit poorly exposed poorly composed low-quality vacation closeup photo in phst artstyle) (with natural lighting and dynamic angles) (that has been poorly shot with a iphone 6 nokia 6600 cell phone camera) by an amateur storm thorgerson) (and uploaded to facebook on 17.05.2012) (and that is capturing the moment of a happy 25 years old woman Sarah) (with extremely detailed skin and round eyes with extremely detailed pupils and irises and brown hair) (wearing a white tshirt in a park) (and taking a selfie while looking into the camera) (in spring with a clear blue sky at noon), abcdefghijklmnopqrstuvwxyz

Negative prompt: yellow hue, (professional studio portrait photography), (long neck, exaggerated cartoon caricature with illogical distorted body proportions), (watermark, text), (belt, straps, bag), (model, red carpet, fashion), (fat, asymmetrical), (instagram, facebook, pexels, unsplash, flickr, shutterstock), (shiny, glossy), (vignette, blur, movie scene, render), (teeth, makeup), abcdefghijklmnopqrstuvwxyz0987654321', 'mixed'::public.prompt_language, 3),
    ('0e0fa0ad-a587-41ea-8e70-5eb23ae0482d'::uuid, '3e88049c-cf07-4c33-8f7e-f7104d1d0273'::uuid, '10000000-0000-4000-8000-000000000006'::uuid, '새벽 아파트 복도', '2000년대 초 피쳐폰으로 찍힌 듯한 한국 구형 아파트 복도와, 어둠 속에 겨우 보이는 실루엣.', '기괴/호러', 'GPT Image 2.0', '3:2', 'Analog Horror', '/samples/analog-horror-apartment-corridor.png', array['아날로그호러', '리미널', '복도', '피쳐폰']::text[], '(found photo:1.4), (old nokia phone camera:1.3), (2002, 2003 digital photo:1.2), low resolution, heavy jpeg compression artifact, digital noise, grain, fluorescent light, yellow-green tint, underexposed shadows, blown highlights, lens distortion, weak vignette, chromatic aberration, (korean apartment corridor:1.4), brutalist concrete hallway, old linoleum floor, brown steel doors, flickering light, dark end of hallway, (silhouette barely visible in darkness:1.3), human figure, tilted head, white chrysanthemum wreath against one door, cardboard boxes, old umbrella, (liminal space:1.2), (uncanny:1.3), subtle horror, something wrong, eerie, unsettling, backrooms aesthetic, no people visible clearly', 'mixed'::public.prompt_language, 4),
    ('b6d219b9-51c8-4747-857b-969fcc2a2e5d'::uuid, '6fc00276-5141-4fd3-8e69-5cbfc451fedc'::uuid, '10000000-0000-4000-8000-000000000006'::uuid, '방과 후 수영장', '오래된 일본 초등학교 수영장 아래에 설명하기 어려운 하얀 형체가 잠긴 장면.', '기괴/호러', 'GPT Image 2.0', '3:2', 'Analog Horror', '/samples/analog-horror-school-pool.png', array['아날로그호러', '수영장', '리미널', '저화질']::text[], '(found photo:1.4), (2001 cheap digital camera:1.3), low megapixel, heavy noise, soft focus, overexposed whites, cyan-tinted shadows, jpeg artifact, slight motion blur, (japanese elementary school outdoor swimming pool:1.4), still water surface, old blue tile, mossy concrete edge, half-open locker room window, blue vinyl hose in pool, small swim cap left on ground, summer afternoon haze, (something submerged in deep end:1.5), white elongated shape underwater, (vaguely human silhouette beneath surface:1.4), photographer shadow visible in water reflection, (liminal space:1.2), (uncanny:1.4), dread, subtle horror, ordinary scene with one impossible detail', 'mixed'::public.prompt_language, 5),
    ('b8356e86-c3c9-4eac-8876-ad169a5c9971'::uuid, '05b85038-f16b-4e1e-8618-02cf789676e6'::uuid, '10000000-0000-4000-8000-000000000006'::uuid, '지하 주차장 의자', '낮인데도 한밤처럼 보이는 한국 아파트 지하 주차장, 빈 의자와 검은 비닐봉지.', '기괴/호러', 'GPT Image 2.0', '3:2', 'Analog Horror', '/samples/analog-horror-parking-garage.png', array['아날로그호러', '주차장', '리미널', '카메라폰']::text[], '(found photo:1.4), (2005 camera phone photo:1.3), low res, digital noise, flash photography, blown highlights near camera, deep darkness beyond flash range, jpeg compression artifact, blue-tinted blacks, (korean underground apartment parking lot:1.4), 1990s concrete construction, yellow stripe reflective tape on pillars, parking lot line markings, early 2000s korean cars parked, hyundai avante, fluorescent ceiling lights, (folding chair alone in empty parking space:1.4), black plastic bag tied to chair leg, handwritten note on pillar illegible due to low resolution, (car idling in dark far end of garage:1.3), faint exhaust smoke, liminal space, uncanny, dread, subtle horror, daytime but feels like midnight, photographer unknown reason for photo', 'mixed'::public.prompt_language, 6),
    ('c431cec7-9dd6-4c69-8427-7a31835df199'::uuid, 'a967d321-451c-4e12-8807-3aa0349ac4a0'::uuid, '10000000-0000-4000-8000-000000000006'::uuid, '모두가 같은 곳을 보는 축제', '일본 시골 마쓰리 사진 속 모든 사람이 화면 밖 같은 방향을 바라보는 군중 호러.', '기괴/호러', 'GPT Image 2.0', '3:2', 'Analog Horror', '/samples/analog-horror-matsuri-crowd.png', array['아날로그호러', '축제', '군중', '마쓰리']::text[], '(found photo:1.4), (2002 budget digicam:1.3), low resolution, noise, grain, soft focus, no flash, twilight, orange streetlamps, blue dusk sky, jpeg artifact, slight motion blur, tourist photo, (japanese rural town summer festival street:1.4), matsuri, yatai food stalls, paper lanterns hanging, people in yukata, all ages crowd, (every single person in photo staring at same direction:1.6), all heads turned left toward camera edge, blank expressions, empty eyes, (nothing visible at left edge of frame, only dark alley:1.3), uncanny, (wrongness:1.5), crowd horror, mass behavior, liminal dread, ordinary festival turned sinister, no blood, no monster', 'mixed'::public.prompt_language, 7),
    ('5d4ad190-a13a-4704-8d28-25c54575042e'::uuid, 'a10bf85d-28e1-4366-84ff-ae2fdb3388ee'::uuid, '10000000-0000-4000-8000-000000000006'::uuid, '병원 복도의 빈 휠체어', '한국 지방 병원 복도 중앙의 빈 휠체어와 유리 반사에만 보이는 형체.', '기괴/호러', 'GPT Image 2.0', '3:2', 'Analog Horror', '/samples/analog-horror-hospital-corridor.png', array['아날로그호러', '병원', '휠체어', '반사']::text[], '(found photo:1.4), (2003 camera phone:1.3), low resolution, digital noise, weak flash, overexposed floor tiles near camera, dim fluorescent beyond, yellow-white hospital light, slightly tilted frame, jpeg artifact, (korean regional hospital corridor:1.4), 2000s interior, beige linoleum, multiple closed patient room doors, one door slightly ajar, (single empty wheelchair in center of hallway:1.5), footrests down, patient gown draped over backrest, (nurse station glass window at end of corridor:1.3), (reflection in glass shows standing figure not present in hallway:1.6), vague silhouette in reflection, no clear face, uncanny wrongness, liminal space hospital, subtle dread, something reflected that shouldn''t exist', 'mixed'::public.prompt_language, 8),
    ('f35706f4-bfe2-4cd6-8ea9-cb296e79caeb'::uuid, 'e7ca6ef8-65c0-4dc2-85d8-92d624542153'::uuid, '10000000-0000-4000-8000-000000000006'::uuid, '아무도 밀지 않는 그네', '낮의 한국 시골 놀이터에서 혼자 높이 올라가 있는 그네와 얼굴이 보이지 않는 아이.', '기괴/호러', 'GPT Image 2.0', '3:2', 'Analog Horror', '/samples/analog-horror-rural-playground.png', array['아날로그호러', '놀이터', '낮공포', '시골']::text[], '(found photo:1.4), (late 1990s disposable camera or early digicam:1.3), underexposed, muted colors, low saturation, jpeg artifact in sky area, vignette, slight grain, no flash outdoor, (rural korean playground:1.4), 1990s rusty iron jungle gym, faded paint, cracked concrete ground, one broken swing hanging crooked, clear afternoon sky but oppressive mood, empty surroundings, rice fields beyond, (child on working swing, back to camera:1.5), no face visible, (swing at high arc, feet off ground:1.3), no adult present anywhere, nobody visible in background, no cars, no buildings nearby, (nobody pushing the swing:1.4), self-swinging impossibility, liminal space, rural isolation, child horror, subtle impossibility, uncanny, dread, sunlit wrongness, daytime horror', 'mixed'::public.prompt_language, 9),
    ('a7d445e1-51a7-4f7f-8aa2-43001a339ae5'::uuid, 'bf6f71b9-1167-4b39-877a-b26bb52c1877'::uuid, '10000000-0000-4000-8000-000000000001'::uuid, '직접 플래시 루프탑 스냅', '인스타 감성의 직접 플래시, 필름 그레인, 럭셔리 에디토리얼 분위기를 섞은 루프탑 스냅.', '사진/시네마틱', 'GPT Image 2.0', '4:5', 'Direct Flash Editorial', '/samples/trend-cinematic-flash-rooftop.png', array['플래시', '필름룩', '인스타트렌드', '스냅']::text[], 'Create a photorealistic vertical 4:5 cinematic street-fashion image from this exact detailed prompt: A stylish anonymous adult fashion subject stands on a high city rooftop just after sunset, wearing an oversized charcoal wool coat, black trousers, and subtle silver accessories. The photo should feel like an expensive but candid lifestyle editorial captured with a compact film camera and a harsh direct flash. Use a wide-angle 28mm lens feeling, slightly imperfect framing, the subject placed a little off-center, city railings and a blurred skyline behind them, warm orange-pink sky fading into blue, direct flash reflecting softly on the coat fabric, natural skin texture, visible fine film grain, tiny dust specks, slight motion blur in one hand, and an unedited snapshot mood. The image must look plausible and photographed, not like a 3D render. Keep the face anonymous and not celebrity-like. Avoid readable text, logos, brand marks, watermarks, extra fingers, distorted hands, plastic skin, over-smoothed beauty retouching, and overly perfect studio lighting.', 'mixed'::public.prompt_language, 10),
    ('cd842e75-feee-4d8b-8348-1fd4a2fa1b06'::uuid, '95c6922a-7f5e-4e86-8627-9b4c182a4ef2'::uuid, '10000000-0000-4000-8000-000000000001'::uuid, '비 오는 택시 창문 폰카', '2000년대 폰카 화질과 비 오는 창문 반사를 이용한 도시 야간 시네마틱 프롬프트.', '사진/시네마틱', 'GPT Image 2.0', '16:9', 'Low Quality Phone Camera', '/samples/trend-cinematic-phone-taxi.png', array['폰카', '저화질', '시네마틱', '인스타트렌드']::text[], 'Create a photorealistic horizontal 16:9 night street image from this exact detailed prompt: A late-night Korean convenience store is seen from inside the back seat of a taxi through a rain-speckled side window. The camera should feel like a cheap 2000s phone camera: low resolution, slight digital zoom, smeared highlights, crushed shadows, mild JPEG compression blocks, and imperfect autofocus. Outside, wet asphalt reflects red, cyan, and green neon, a blurred passerby with a transparent umbrella crosses the frame, the convenience store lights are overexposed and fluorescent, and the taxi interior edge is barely visible as a dark soft silhouette at the bottom. The mood is mundane but cinematic, like a real found photo from a rainy city night. Add subtle window droplets in sharp foreground and a soft, hazy background. Do not include readable store signs, logos, brand names, watermarks, clear license plates, fake timestamps, cartoon styling, or overly clean HDR rendering.', 'mixed'::public.prompt_language, 11),
    ('5e38bbbf-af6b-4c58-8b07-9d8376c3ab4d'::uuid, '3b9d30fa-0ca2-4dfc-86f8-06907d77acba'::uuid, '10000000-0000-4000-8000-000000000001'::uuid, '네온 골목 다큐멘터리 컷', '비 온 뒤 골목, 푸드카트 수증기, 택시 헤드라이트를 합친 다큐멘터리풍 야간 사진.', '사진/시네마틱', 'GPT Image 2.0', '16:10', 'Documentary Night Photo', '/samples/trend-cinematic-neon-alley.png', array['네온', '거리사진', '포토리얼', '필름룩']::text[], 'Create a photorealistic 16:10 documentary night street photograph from this exact detailed prompt: A dense Seoul side alley after heavy rain, seen from pedestrian eye level with a 35mm film camera. The pavement is wet and uneven, reflecting red, cyan, and white neon from small restaurants and bars, but all signs must be unreadable abstract light shapes. A small food cart releases white steam near the middle ground, taxi headlights cut diagonally through the mist from the far end of the alley, and a few distant human silhouettes are blurred enough to be anonymous. The composition should feel cinematic but still natural, with deep shadows, realistic lens bloom, mild halation around neon, fine 35mm film grain, slight handheld tilt, and layered depth from foreground puddles to background haze. Color grade: cool blue shadows with warm red practical lights. Avoid fantasy elements, perfect symmetry, over-sharpened HDR, readable Korean text, logos, watermarks, clean studio lighting, and faces looking directly at camera.', 'mixed'::public.prompt_language, 12),
    ('3b6b1a38-c376-4d11-800d-959f88c2880d'::uuid, 'cfbe3088-0b5d-44a4-838c-8e03b782f7e7'::uuid, '10000000-0000-4000-8000-000000000001'::uuid, '사이버 마스크 패션 포트레이트', 'Civitai 월간 반응순에서 강했던 다크 사이버 패션 포트레이트 흐름을 새로 재구성한 프롬프트.', '인물/패션', 'GPT Image 2.0', '4:5', 'Cyberpunk Fashion Editorial', '/samples/trend-fashion-cyber-mask.png', array['패션', '사이버펑크', 'Civitai', '필름그레인']::text[], 'Create a vertical 4:5 high-fashion editorial portrait from this exact detailed prompt: An anonymous adult fashion model is photographed in a dark cyberpunk studio wearing a black translucent face veil, a sculptural chrome shoulder harness, and a matte black high-neck garment. The styling should feel avant-garde and expensive rather than costume-like. Use a three-quarter pose with the head slightly turned toward camera, black sclera inspired contact lenses or very dark reflective eyes, red neon rim light on the shoulders, a cool dim key light from above, and deep chiaroscuro shadows across the face veil. Add gritty film grain, subtle chromatic aberration on the red highlights, a hint of motion in the veil fabric, and a shallow depth of field. The image should look like a real editorial fashion photograph with dramatic post-processing, not an anime image. Keep all anatomy elegant and believable. Avoid readable text, logos, brand names, watermark, gore, monstrous deformation, extra limbs, plastic skin, glossy toy-like armor, and celebrity likeness.', 'mixed'::public.prompt_language, 13),
    ('8d760bd6-c63b-4b27-80f2-fbe6e2400ab4'::uuid, '59faf30a-3c06-4222-86c1-81f226b8bc00'::uuid, '10000000-0000-4000-8000-000000000001'::uuid, '한복 테크웨어 에디토리얼', '전통 실루엣과 테크웨어 소재감을 섞은 차분한 패션 화보 프롬프트.', '인물/패션', 'GPT Image 2.0', '4:5', 'Hanbok Techwear Editorial', '/samples/trend-fashion-hanbok-techwear.png', array['패션', '한복', '테크웨어', '화보']::text[], 'Create a vertical 4:5 fashion editorial portrait from this exact detailed prompt: An anonymous adult Korean model stands in a quiet concrete museum interior wearing a modern ivory jacket inspired by hanbok structure and techwear construction. The garment has a softly crossed collar, layered wrap panels, matte technical fabric, subtle reflective piping along the seams, hidden fasteners, and a slightly oversized silhouette. Use a calm full-body or three-quarter composition with the model centered but surrounded by negative space, soft skylight entering from high windows, pale concrete walls, a polished stone floor with faint reflection, and restrained luxury magazine styling. The mood should be elegant, Korean, contemporary, and wearable, not costume or fantasy. Use an 85mm portrait lens feeling, shallow depth of field, accurate fabric texture, natural hands, and subdued warm-gray color grading. Avoid readable text, logos, brand labels, ornate historical costume exaggeration, celebrity likeness, distorted fingers, extra limbs, plastic skin, and over-saturated colors.', 'mixed'::public.prompt_language, 14),
    ('ac711cbe-bf16-412f-82bf-b091124c93f0'::uuid, 'fef04c24-4303-482f-8a1c-6b473f71374d'::uuid, '10000000-0000-4000-8000-000000000001'::uuid, '수중 실버 패브릭 화보', '인물 화보에서 자주 쓰이는 수중 부유감과 실버 패브릭을 결합한 몽환적 이미지 프롬프트.', '인물/패션', 'GPT Image 2.0', '3:4', 'Underwater Editorial', '/samples/trend-fashion-underwater-silver.png', array['수중', '화보', '패션', '몽환']::text[], 'Create a vertical 3:4 dreamlike underwater fashion editorial image from this exact detailed prompt: An anonymous adult model floats weightlessly in dark blue water, wrapped in long translucent silver fabric that moves like slow smoke around the body. The pose is elegant and calm, with arms relaxed, hair drifting naturally, and the face partially turned away so the person feels anonymous. Light rays enter from the top left and fade into deep blue shadow, tiny air bubbles rise around the fabric edges, and the silver textile catches soft highlights without looking metallic or fake. The image should feel like a luxury fashion magazine shoot captured underwater with a high-end camera, realistic skin tones, real fabric drag, soft suspended particles, and a quiet cinematic mood. Composition should leave negative space above the subject and preserve a vertical poster feeling. Avoid mermaid elements, fantasy creatures, visible pool tiles, readable text, logos, watermark, distorted limbs, extra fingers, stiff doll anatomy, over-sharpening, and cartoon or anime styling.', 'mixed'::public.prompt_language, 15),
    ('0971e252-b6b5-4016-8ad8-101086a71e52'::uuid, 'c91355c1-984c-4361-8f0e-f519091f4c1e'::uuid, '10000000-0000-4000-8000-000000000002'::uuid, '앰버 향수 빈티지 광고', '실크, 연기, 앰버 조명으로 고급 향수 광고컷을 만드는 제품사진 프롬프트.', '제품/광고', 'GPT Image 2.0', '1:1', 'Luxury Product Ad', '/samples/trend-product-amber-perfume.png', array['제품사진', '향수', '광고', '럭셔리']::text[], 'Create a square 1:1 premium product advertisement image from this exact detailed prompt: A nameless translucent glass perfume bottle sits on rippled champagne silk fabric, photographed as a luxury fragrance advertisement with no brand text. The bottle should have a heavy glass base, a simple rectangular silhouette, a clear cap, and warm amber liquid inside. Use a low side angle with an 80mm macro lens feeling, warm amber side light from the left, a narrow white highlight along the glass edge, a soft dark background, delicate smoke drifting behind the bottle, tiny water droplets on the glass, and realistic caustic reflections on the silk. The composition should feel like a 1970s luxury magazine still life mixed with modern clean product photography. The image must be highly polished but believable, with accurate glass refraction and fabric folds. Avoid any readable label, logo, brand mark, watermark, fake typography, extra bottles, messy props, floating bottle, warped cap, and over-saturated orange color.', 'mixed'::public.prompt_language, 16),
    ('251bfcdc-cc42-4553-8519-0e6aa0d6803c'::uuid, '9706ab69-a1d5-4d07-890c-4accbbd6f9cf'::uuid, '10000000-0000-4000-8000-000000000002'::uuid, '녹차 세럼 스톤 제품컷', '화산석, 물방울, 녹차잎을 이용한 한국 스킨케어 상세페이지용 제품 이미지.', '제품/광고', 'GPT Image 2.0', '1:1', 'Skincare Product Shot', '/samples/trend-product-green-tea-serum.png', array['제품사진', '화장품', '스킨케어', '상세페이지']::text[], 'Create a square 1:1 clean skincare product advertisement image from this exact detailed prompt: A translucent unbranded glass serum bottle with a matte white dropper cap stands on wet black volcanic stone, surrounded by a few fresh green tea leaves and tiny beads of water. The scene should feel like a premium Korean skincare campaign: minimal, calm, botanical, and high-end. Use soft diffused studio light from the upper left, a subtle green bounce reflection in the glass, realistic water droplets on the bottle and stone, a shallow depth of field with the foreground stone sharp and background softly blurred, and a restrained color palette of black, clear glass, pale green, and soft white. The bottle may have a blank frosted label area but absolutely no readable letters or brand marks. Make the glass refraction and shadows physically believable. Avoid logos, readable text, crowded props, fake plant clutter, plastic-looking bottle, floating objects, deformed dropper, excessive glow, oversaturated green, and watermark.', 'mixed'::public.prompt_language, 17),
    ('10440d24-d9b2-46ae-8997-c1ecaa5998a0'::uuid, 'e019886c-a726-4787-82f4-e80250364a2c'::uuid, '10000000-0000-4000-8000-000000000002'::uuid, '무광 블랙 스피커 랜딩컷', '스타트업 랜딩페이지에 바로 쓸 수 있는 무광 테크 제품 광고 이미지 프롬프트.', '제품/광고', 'GPT Image 2.0', '16:9', 'Tech Product Landing', '/samples/trend-product-matte-speaker.png', array['제품사진', '테크', '스튜디오', '랜딩']::text[], 'Create a horizontal 16:9 commercial tech product photograph from this exact detailed prompt: A matte black unbranded wireless speaker sits on a clean rectangular concrete plinth in a minimal studio set. The speaker should have a simple cylindrical-rectangular hybrid shape, fine woven acoustic mesh texture, one small blank recessed control area with no symbols, and a premium tactile finish. Use a dramatic large softbox from the upper left, a precise shadow falling to the right, a very subtle cool cyan rim light along the back edge, and a dark gray seamless background. The composition should have generous negative space for a landing page hero, with the product placed slightly left of center and viewed from a low three-quarter angle. Show realistic material texture, dust-free but not plastic, believable contact shadow, and crisp product photography focus. Avoid logos, readable text, brand marks, buttons with symbols, duplicate speakers, floating object, warped geometry, excessive reflections, colorful gradient background, watermark, and toy-like CGI appearance.', 'mixed'::public.prompt_language, 18),
    ('5b36b6bc-7f56-4a78-8b8f-908e56eaf8ec'::uuid, 'e565f33d-66dd-4ce0-87f3-abeb6eb9df7c'::uuid, '10000000-0000-4000-8000-000000000003'::uuid, '레드 코어 메카 가디언', 'Civitai의 다크 레드 메카 계열 인기 메타데이터를 바탕으로 만든 오리지널 게임 키비주얼.', '캐릭터/웹툰', 'GPT Image 2.0', '3:4', 'Anime Mecha Key Visual', '/samples/trend-character-red-mecha.png', array['메카', '게임원화', 'Civitai', '키비주얼']::text[], 'Create a vertical 3:4 polished anime game key visual from this exact detailed prompt: An original dark red mecha guardian robot stands alone in heavy rain on a smoky battlefield at night. The mecha should have angular black and gunmetal armor, a glowing red circular core in the chest, narrow red sensor eyes, large protective shoulder plates, wet metal surfaces with rain streaks, and battle-worn scratches without looking broken. Use a dynamic low-angle composition so the robot feels huge and protective, with one arm lowered and one arm slightly raised as if blocking danger. Background: ruined industrial silhouettes, drifting smoke, red warning lights blurred in the distance, rain illuminated by the core glow. Visual style: crisp anime game key art with painterly lighting, sharp silhouette, high detail, cinematic contrast, and controlled red accents. Avoid existing franchise resemblance, logos, readable text, watermark, human pilots, gore, excessive weapons, deformed limbs, toy-like plastic, and cluttered background.', 'mixed'::public.prompt_language, 19),
    ('2b82442b-93d5-4997-8d8f-a4e2a693fe03'::uuid, '66cd7ad2-39f6-496d-8888-5285672b1f66'::uuid, '10000000-0000-4000-8000-000000000003'::uuid, '크리스털 포션 아이콘', '픽셀아트 평가 태그와 RPG 아이템 아이콘 구성을 합친 게임 리소스 프롬프트.', '캐릭터/웹툰', 'GPT Image 2.0', '1:1', 'Pixel Art Item Icon', '/samples/trend-character-crystal-potion.png', array['게임', '아이콘', '픽셀아트', '아이템']::text[], 'Create a square 1:1 cute high-resolution pixel-art inspired RPG inventory icon from this exact detailed prompt: A single original crystal potion bottle with tiny translucent wings is centered on a dark vignette background. The bottle is small, round, and faceted like cut glass, filled with glowing violet-blue liquid and a floating star-shaped crystal inside. The wings should be delicate and symmetrical, attached near the neck of the bottle, with a tiny cork stopper wrapped in gold thread. The style should resemble a polished game item icon: crisp silhouette, readable shape at small size, pixel-art influence with clean chunky highlights, but rendered at high resolution with jewel-like sparkle and controlled lighting. Use a soft circular glow behind the item, tiny particle specks, and a subtle drop shadow so it feels ready for an inventory grid. Avoid text, numbers, UI labels, logos, watermark, multiple items, hands, character face, messy background, blurry edges, and overly realistic product photography.', 'mixed'::public.prompt_language, 20),
    ('eea212c4-6f93-4377-8b7e-7e268746e8be'::uuid, '647248b5-17b4-4ba1-8951-88568a9f7c87'::uuid, '10000000-0000-4000-8000-000000000003'::uuid, '서울 루프탑 마법사 키비주얼', '웹툰 커버처럼 바로 읽히는 서울 루프탑 판타지 캐릭터 프롬프트.', '캐릭터/웹툰', 'GPT Image 2.0', '3:4', 'Korean Webtoon Cover', '/samples/trend-character-rooftop-mage.png', array['웹툰', '캐릭터', '판타지', '키비주얼']::text[], 'Create a vertical 3:4 Korean webtoon cover style character illustration from this exact detailed prompt: An original young adult mage stands on the roof of a Seoul apartment building at sunset, wearing a long dark coat inspired by a school uniform but modified with fantasy details: brass buttons, a loose tie, layered cuffs, and subtle embroidered talisman patterns. Around the character, glowing paper talismans float in a circular motion, casting warm orange light on the coat and face. The background shows rooftop railings, distant apartment blocks, water tanks, antennas, and a dramatic orange sky fading into purple. Use clean webtoon line art with painterly lighting, crisp facial features, expressive but not exaggerated eyes, dynamic wind in hair and coat hem, and a polished key visual composition suitable for a fantasy webtoon poster. Keep all text absent. Avoid existing anime or webtoon character likeness, logos, readable Korean writing on talismans, watermark, deformed hands, extra fingers, messy anatomy, and over-cluttered magic effects.', 'mixed'::public.prompt_language, 21),
    ('054b6fd9-9609-438a-8923-3fc7a984b140'::uuid, '8a699f93-590c-45eb-861b-ec1470d12952'::uuid, '10000000-0000-4000-8000-000000000004'::uuid, '호수 위 유리 온실 카페', '아이소메트릭 3D 미니어처 스타일로 만든 아침 호수 위 온실 카페.', '3D/공간', 'GPT Image 2.0', '1:1', 'Isometric Miniature 3D', '/samples/trend-3d-greenhouse-cafe.png', array['3D', '아이소메트릭', '카페', '미니어처']::text[], 'Create a square 1:1 cozy isometric 3D render from this exact detailed prompt: A tiny glass greenhouse cafe floats on a calm lake at sunrise, designed like a miniature diorama viewed from an elevated isometric angle. The cafe has transparent glass walls with thin dark metal frames, a warm wooden floor, a small counter inside, hanging plants, a few round tables, and amber interior lights glowing through early morning fog. A narrow wooden deck wraps around the greenhouse with two empty chairs and potted herbs. The surrounding lake surface is mirror-calm with soft ripples, pale mist, and a reflection of the glass structure. Use high-detail 3D rendering with miniature scale, soft global illumination, realistic glass transparency, cozy warm-cool color contrast, and clean composition centered in frame. Avoid readable signs, logos, people, cluttered furniture, fantasy castles, impossible perspective, harsh shadows, flat cartoon look, watermark, and text.', 'mixed'::public.prompt_language, 22),
    ('6908174e-2b9e-4f78-8f29-78da7b2eef51'::uuid, '33ae04ce-e403-4ab1-820c-0a6c02a841b1'::uuid, '10000000-0000-4000-8000-000000000004'::uuid, '네온 레트로웨이브 미니시티', 'Civitai의 retrowave 도시 풍경 흐름을 3D 미니어처 도시로 재구성한 프롬프트.', '3D/공간', 'GPT Image 2.0', '16:9', 'Retrowave 3D City', '/samples/trend-3d-retrowave-city.png', array['3D', '레트로웨이브', 'Civitai', '도시']::text[], 'Create a horizontal 16:9 neon retrowave miniature cityscape from this exact detailed prompt: A small futuristic city is built like a glossy miniature model on a black reflective surface. In the background, a huge glowing orange sun sits low behind simplified purple mountains under a deep starry dusk sky. The city has compact geometric towers, thin neon strips, tiny elevated roads, and wet black streets reflecting magenta, cyan, and orange light. The overall mood should be synthwave album-cover energy but rendered as a clean high-detail 3D miniature, not a flat illustration. Use strong perspective leading lines toward the sun, controlled bloom on neon, crisp silhouettes, and atmospheric haze near the mountains. Keep the palette balanced between black, orange, magenta, cyan, and violet. Avoid readable text, logos, retro typography, cars with brand marks, people in foreground, oversaturated chaos, flat poster graphics, watermark, and distorted architecture.', 'mixed'::public.prompt_language, 23),
    ('d2c5a127-a4e7-4594-81fe-2016dbeca991'::uuid, 'a1ab4f25-22c7-447a-82f4-cb25fcf84eba'::uuid, '10000000-0000-4000-8000-000000000004'::uuid, '클레이 스톱모션 침실', '손으로 만든 듯한 질감과 따뜻한 조명을 살린 클레이 애니메이션풍 방 렌더.', '3D/공간', 'GPT Image 2.0', '1:1', 'Clay Stop-Motion Room', '/samples/trend-3d-clay-bedroom.png', array['3D', '클레이', '미니어처', '방']::text[], 'Create a square 1:1 cozy clay animation style bedroom render from this exact detailed prompt: A small handmade bedroom diorama made entirely in clay and stop-motion materials. The room has a low bed with a soft wrinkled blanket, a small wooden desk, a warm desk lamp, stacked books, a tiny potted plant, a round rug, a window with soft evening light, and slightly imperfect handmade furniture. Every surface should show tactile clay fingerprints, tiny tool marks, rounded edges, and subtle irregularities like a real stop-motion set. Use warm amber lamp light balanced with cool blue window light, shallow depth of field, miniature scale, and a charming quiet mood. The camera looks slightly downward from a corner of the room, making the space feel lived-in and cozy. Avoid realistic human figures, readable book titles, logos, watermark, flat vector style, plastic toy shine, overly perfect geometry, clutter that hides the room layout, and excessive beige monotone.', 'mixed'::public.prompt_language, 24),
    ('15870560-e75f-47a8-8645-a475de75d696'::uuid, '0340828f-29cb-461d-89d2-7a870599a294'::uuid, '10000000-0000-4000-8000-000000000005'::uuid, 'Y2K 홀로그램 매거진 콜라주', '홀로그램 스티커, 크롬 별, 컷아웃을 사용한 인스타식 Y2K 편집 프롬프트.', '편집/콜라주', 'GPT Image 2.0', '4:5', 'Y2K Magazine Collage', '/samples/trend-edit-y2k-collage.png', array['Y2K', '콜라주', '인스타트렌드', '매거진']::text[], 'Create a vertical 4:5 Y2K magazine collage lookbook image from this exact detailed prompt: A polished editorial collage page featuring anonymous fashion portrait cutouts arranged like a late-1990s / early-2000s glossy magazine spread. Use two or three cropped model photos as paper cutouts with no recognizable celebrity, layered over holographic sticker shapes, chrome stars, translucent plastic frames, tiny decorative UI icons, faux barcode blocks with no readable numbers, soft airbrush gradients, and reflective magazine paper texture. The layout should feel energetic and trendy but still professionally designed, with clear visual hierarchy and negative space. Use a palette of silver, icy blue, hot pink accents, black outlines, and pearly white highlights. Add tape pieces, scanner texture, halftone dots, and subtle paper shadows to make the collage physical. All microtext must be abstract scribbles, not real words. Avoid readable text, logos, brand names, watermark, messy clutter, distorted faces, extra limbs, and low-quality random sticker chaos.', 'mixed'::public.prompt_language, 25),
    ('8816fc81-03ba-47b5-83a6-e6e3d19f35fc'::uuid, 'e307d3d4-a063-4a5d-89fb-d504b8f7306b'::uuid, '10000000-0000-4000-8000-000000000003'::uuid, '가챠 카드 결과 화면', '게임 UI, 희귀도 프레임, 보석 파티클을 한 장에 모은 가챠 결과 화면 프롬프트.', '편집/콜라주', 'GPT Image 2.0', '9:16', 'Mobile Game UI Edit', '/samples/trend-edit-gacha-card.png', array['게임UI', '가챠', '편집', '캐릭터']::text[], 'Create a vertical 9:16 anime mobile game gacha result screen from this exact detailed prompt: An original fantasy character appears in the center of a polished mobile game gacha result interface. The character is a young adult star knight with a short cape, luminous armor accents, and a crystal sword held downward in a calm victory pose. Around the character is a glowing rarity frame made of gold and violet light, gem particles, radial burst rays, floating shards, and layered translucent UI panels. The screen should clearly feel like a gacha pull result without copying any existing game: top and bottom interface bars, circular icons, empty stat panels, decorative unreadable glyph labels, and a large central card frame. The design should be clean, premium, and readable as UI, with deep navy background, violet highlights, gold accents, and sparkling particle effects. Avoid real words, readable letters, logos, brand marks, copyrighted game resemblance, watermark, distorted hands, extra fingers, cramped composition, and messy UI clutter.', 'mixed'::public.prompt_language, 26),
    ('054540dc-fb34-44c8-89fa-e63bcd571cb6'::uuid, '6e039778-b77f-4e6c-8dc9-60486358dc4b'::uuid, '10000000-0000-4000-8000-000000000003'::uuid, '낙서장 캐릭터 콘셉트 시트', '스케치, 스티커, 화살표, 메모 박스를 섞은 콘셉트 시트형 콜라주 프롬프트.', '편집/콜라주', 'GPT Image 2.0', '1:1', 'Doodle Concept Sheet', '/samples/trend-edit-doodle-sheet.png', array['낙서장', '콜라주', '캐릭터시트', '프롬프트공유']::text[], 'Create a square 1:1 doodle sketchbook collage character concept sheet from this exact detailed prompt: A messy but appealing creative desk scene showing an open sketchbook page filled with concept art for one original cute streetwear mascot character. The mascot is a small round character wearing oversized sneakers, a hoodie, and a tiny crossbody bag. Show the character repeated in several forms: a clean front pose, a side pose, a rough action pose, two facial expression thumbnails, a color swatch strip, and sticker-like cutout versions taped onto the page. Use rough pencil lines, marker strokes, watercolor stains, tiny arrows, boxes, circles, and decorative unreadable scribbles that look like notes without forming real words. The page should feel like an artist prompt notebook shared online, playful and practical. Add pens, tape, and paper texture around the sketchbook, but keep the main character readable. Avoid real text, logos, watermark, copyrighted mascot resemblance, distorted anatomy, random unrelated characters, clutter covering the drawings, and overly polished vector art.', 'mixed'::public.prompt_language, 27),
    ('066de9bc-c4d0-4235-88ef-7f02a5b3a513'::uuid, '12f1f130-1a4b-49c5-8e7d-ce683d912c3d'::uuid, '10000000-0000-4000-8000-000000000006'::uuid, 'VHS 생일파티 거울 그림자', '가정용 VHS 테이프 속 거울 반사에만 보이는 사람 형상으로 만드는 은근한 공포.', '기괴/호러', 'GPT Image 2.0', '4:3', 'VHS Analog Horror', '/samples/trend-horror-vhs-birthday.png', array['VHS', '아날로그호러', '인스타트렌드', '언캐니']::text[], 'Create a 4:3 VHS analog horror still from this exact detailed prompt: A low-resolution frame from a 1994 family birthday tape in a suburban dining room. The camera is placed at table height, slightly tilted, as if held by a parent using an old camcorder. A birthday cake with a few lit candles sits in the foreground, plastic plates and cups are scattered around, and warm yellow home-video lighting fills the room. The family members should be out of frame or blurred anonymous silhouettes at the edges; the focus is the room itself. In the hallway mirror behind the table, a tall person-shaped shadow appears clearly, but no matching person exists in the actual hallway. The horror should be subtle and uncanny, not graphic. Add heavy VHS scanlines, chromatic bleed, soft tracking noise, crushed blacks, mild tape warping near the bottom, and a blurred timestamp area with no readable numbers. Avoid blood, gore, obvious monster face, readable text, logos, watermark, modern furniture, crisp HD quality, and jump-scare composition.', 'mixed'::public.prompt_language, 28),
    ('95f3b472-e89b-4cb9-87bf-8a72311b4726'::uuid, 'd082ffeb-d5f9-45c5-8fd8-73a54ea66c73'::uuid, '10000000-0000-4000-8000-000000000006'::uuid, '낮의 빈 쇼핑몰 푸드코트', '인스타에서 규모가 큰 liminal spaces 흐름을 쇼핑몰 푸드코트 사진으로 만든 프롬프트.', '기괴/호러', 'GPT Image 2.0', '3:2', 'Liminal Space Photo', '/samples/trend-horror-liminal-mall.png', array['리미널', '쇼핑몰', '인스타트렌드', '저화질']::text[], 'Create a 3:2 liminal space horror photograph from this exact detailed prompt: An abandoned 1990s shopping mall food court at noon, photographed with a slightly faded disposable camera. The space is sunlit but empty, with rows of plastic chairs and laminate tables arranged too perfectly, old tiled flooring, a closed escalator in the background, dark storefront openings, dusty skylight beams, and a few dead potted plants. The composition should be wide and still, with a subtle fisheye distortion and the feeling that the mall was vacated minutes ago even though it has been empty for years. Colors should be washed-out beige, pale teal, and weak yellow sunlight, with soft grain, mild vignetting, and realistic dust. Make the horror come from silence, scale, and absence, not from creatures. Avoid people, readable store signs, logos, brand names, blood, gore, monsters, graffiti text, watermark, cinematic fog overload, and modern luxury mall design.', 'mixed'::public.prompt_language, 29),
    ('57cba67d-913c-4390-8d15-08a5ce3e1e63'::uuid, '3a36478b-d338-4f39-83b2-413fbad91b24'::uuid, '10000000-0000-4000-8000-000000000006'::uuid, '교실 단체사진의 빈 의자', '스캔된 단체사진의 어긋난 초점과 앞줄의 빈 의자로 만드는 언캐니 호러 프롬프트.', '기괴/호러', 'GPT Image 2.0', '4:3', 'Uncanny Scanned Photo', '/samples/trend-horror-yearbook-chair.png', array['언캐니', '단체사진', '저화질', '기괴']::text[], 'Create a 4:3 uncanny early-2000s scanned school group photo from this exact detailed prompt: A low-resolution scanned classroom group portrait with an unsettling empty chair in the front row. The scene is a generic Korean classroom from the early 2000s with desks pushed aside, fluorescent ceiling lights, pale green walls, old curtains, and a chalkboard in the background with no readable writing. Several anonymous young adult or late-teen students stand and sit in rows, but every face is slightly motion-blurred, underexposed, or turned just enough to avoid clear identity. The front row contains one perfectly centered empty chair that is sharper than the people around it. The image should feel like a real printed photo scanned years later: dust on scanner glass, faded colors, slight paper bend, compression noise, and uneven exposure. The horror should be subtle and psychological, focused on the empty chair. Avoid readable names, school logos, gore, ghosts, obvious monster, childlike closeups, identifiable faces, watermark, modern classroom equipment, and clean professional photography.', 'mixed'::public.prompt_language, 30),
    ('36d7d3b4-336a-4ea1-8c34-a8b6496cbfc1'::uuid, 'e14525bf-7321-4552-877c-43cc6d4ffe56'::uuid, '10000000-0000-4000-8000-000000000004'::uuid, '고대 숲속 마법 도서관', '세계관 배경용으로 쓰기 좋은 거대한 나무 속 도서관 콘셉트아트 프롬프트.', '배경/세계관', 'GPT Image 2.0', '16:9', 'Fantasy Environment Concept', '/samples/trend-world-forest-library.png', array['세계관', '판타지', '도서관', '컨셉아트']::text[], 'Create a horizontal 16:9 epic fantasy environment concept art image from this exact detailed prompt: A vast magical library is built inside and between ancient living trees in a misty forest. Enormous tree trunks form the structural columns, with carved wooden balconies, spiral staircases wrapped around roots, glowing shelves embedded into bark, hanging lanterns, moss-covered reading platforms, and bridges connecting different levels. The camera is a wide establishing shot from a slightly low angle, showing the scale of the library rising into the canopy while a misty forest is visible through arched openings. Use warm candlelight and golden shelf glow against cool green-blue forest fog, floating dust particles, soft volumetric light beams, and richly detailed wood texture. The scene should feel inhabitable and worldbuilding-focused, not just decorative. Include tiny distant silhouettes only for scale, not as main characters. Avoid readable book titles, signs, logos, watermark, modern furniture, over-bright fantasy colors, flat illustration, and chaotic clutter.', 'mixed'::public.prompt_language, 31),
    ('0c07560c-adde-408a-8924-e175dc694885'::uuid, '793d3d0e-0958-4f22-8165-fb6e3d06e373'::uuid, '10000000-0000-4000-8000-000000000004'::uuid, '솔라펑크 옥상 도시', '녹지 옥상, 태양광 유리, 아침 안개를 사용한 낙관적인 솔라펑크 도시 배경.', '배경/세계관', 'GPT Image 2.0', '16:9', 'Solarpunk Worldbuilding', '/samples/trend-world-solarpunk-terrace.png', array['세계관', '솔라펑크', '도시', '배경']::text[], 'Create a horizontal 16:9 solarpunk city terrace worldbuilding concept art image from this exact detailed prompt: A layered ecological megacity seen from a high rooftop terrace in the morning. The architecture is soft white concrete, pale timber, and solar glass, with curved balconies, public gardens, green roofs, water channels, and vertical farms built into the city blocks. In the foreground, a communal rooftop garden has vegetable beds, small trees, shaded seating, and transparent solar panels catching warm morning light. In the distance, multiple terraces step down into a bright hazy skyline, with tiny anonymous silhouettes for scale only. The mood should be optimistic, clean, and plausible rather than fantasy, with atmospheric haze, soft sunlight, realistic vegetation, and a calm civic design language. Use a balanced palette of white, fresh green, warm gold, and clear sky blue. Avoid logos, readable signage, flying cars, cyberpunk darkness, excessive utopian gloss, text, watermark, crowded people, and one-note green monotony.', 'mixed'::public.prompt_language, 32),
    ('2658de28-6133-4771-8cf8-615a6ecb5e5a'::uuid, '6ee28f32-12a3-4bcf-8899-2439a27ea453'::uuid, '10000000-0000-4000-8000-000000000004'::uuid, '사막 위 부유하는 검은 모노리스', '미니멀한 SF 영화 오프닝처럼 보이는 사막 모노리스 세계관 프롬프트.', '배경/세계관', 'GPT Image 2.0', '21:9', 'Sci-Fi Environment Concept', '/samples/trend-world-desert-monolith.png', array['SF', '사막', '모노리스', '컨셉아트']::text[], 'Create a wide 21:9 science fiction environment concept art image from this exact detailed prompt: A vast desert salt flat at pale sunrise, cracked white ground stretching to the horizon, with a single enormous black monolith hovering silently several meters above the surface. The monolith is perfectly smooth, vertical, rectangular, and slightly reflective, casting a soft impossible shadow through dusty morning air. Far below it, a tiny research convoy of two rover-like vehicles and a few small anonymous silhouettes provide scale, but they must remain distant and secondary. Use minimalist cinematic composition with the monolith slightly off-center, a huge sky, low warm sunlight, thin atmospheric dust, and restrained colors: pale sand, silver blue sky, black monolith, faint orange horizon. The mood should be mysterious, lonely, and monumental, like a serious sci-fi film establishing shot. Avoid logos, readable text, alien creatures, explosions, excessive spaceships, fantasy magic, watermark, cluttered foreground, and over-detailed noisy design.', 'mixed'::public.prompt_language, 33),
    ('db65df71-cabe-42ef-8a03-050a1182ad28'::uuid, 'd625f991-c920-4872-8c66-aa5332362d23'::uuid, '10000000-0000-4000-8000-000000000003'::uuid, '2010년대 학원 로맨스 버스정류장', '2010년대 한국 학원 로맨스 웹툰의 정서를 실사 청춘 영화 스틸처럼 바꾼 프롬프트.', '사진/시네마틱', 'GPT Image 2.0', '4:5', '2010s Korean Youth Live Action', '/samples/instagram-webtoon-bus-stop.png', array['인스타트렌드', '웹툰실사화', '2010년대', '학원로맨스']::text[], 'Create a vertical 4:5 photorealistic live-action still from this exact detailed prompt: A nostalgic 2010s Korean school-romance webtoon mood reimagined as a real photograph, without referencing any existing title or character. Two anonymous young adult actors dressed as high-school students stand at a small neighborhood bus stop after light rain, one holding a transparent umbrella and the other holding a paperback workbook and a cheap wired earphone. The setting should feel like Korea around 2012: old apartment blocks in the background, a faded bus route sign with no readable text, damp pavement, convenience-store glow far behind them, and a soft overcast blue-gray evening sky. Use a 50mm lens feeling, shallow depth of field, natural skin texture, subdued school-uniform fabric, gentle awkward distance between the two characters, and the emotional tone of first love before anyone says anything. Color grade should be muted pastel with realistic rain reflections and a slightly compressed early digital camera softness. Avoid existing webtoon characters, celebrity likeness, readable signage, logos, explicit romance, kissing, exaggerated drama, plastic skin, extra fingers, watermark, and anime/cartoon rendering.', 'mixed'::public.prompt_language, 34),
    ('84c74c47-c502-478f-82a7-fbf8951b5cd2'::uuid, 'f757a008-8852-4555-8f1d-2c5632780aa6'::uuid, '10000000-0000-4000-8000-000000000003'::uuid, '방과 후 분식집 청춘 스틸', '분식집, 교복, 오렌지 형광등으로 만드는 2010년대 한국 웹툰 실사화 분위기.', '사진/시네마틱', 'GPT Image 2.0', '16:9', 'Korean Youth Drama Still', '/samples/instagram-webtoon-snack-bar.png', array['인스타트렌드', '웹툰실사화', '분식집', '청춘']::text[], 'Create a horizontal 16:9 photorealistic 2010s Korean after-school scene from this exact detailed prompt: A nostalgic live-action reinterpretation of early-2010s Korean school webtoon atmosphere, set inside a tiny neighborhood snack bar after school. Three anonymous young adult actors dressed as students sit around a metal table with tteokbokki, fish cake soup, paper cups, and cheap notebooks. The room has orange fluorescent lighting, plastic menu boards with all text blurred and unreadable, condensation on the window, old posters reduced to abstract color blocks, and school bags on the floor. The image should feel like a still from a youth drama made from a webtoon, warm but ordinary, with real awkward friendships, not polished idol styling. Use a slightly soft early DSLR look, 35mm lens, natural expressions, imperfect posture, realistic food steam, muted red-orange palette, and shallow background blur. Avoid existing webtoon titles or characters, readable Korean text, logos, brand labels, celebrity likeness, romance overacting, kissing, anime style, extra fingers, distorted hands, watermark, and overly glossy K-drama lighting.', 'mixed'::public.prompt_language, 35),
    ('4f7f18e4-d771-4581-83cb-a3bb9ac72d02'::uuid, '2fbfd8af-32d9-4e46-8dfd-e2ce60b5ca40'::uuid, '10000000-0000-4000-8000-000000000004'::uuid, '싸이월드 감성 방바닥 셀카', '스티커 사진, MP3, 플립폰, 책상 조명으로 만든 2010년대 한국 방 사진 프롬프트.', '사진/시네마틱', 'GPT Image 2.0', '1:1', 'Early Digital Camera Nostalgia', '/samples/instagram-webtoon-cyworld-room.png', array['인스타트렌드', '2010년대', '방사진', '디카감성']::text[], 'Create a square 1:1 photorealistic nostalgic bedroom selfie scene from this exact detailed prompt: A 2010s Korean teen-room atmosphere reimagined as a real photo, inspired by old social media diary and sticker-photo culture but without copying any real platform UI. An anonymous young adult student sits on the floor of a small bedroom wearing casual school sportswear, surrounded by a flip phone, old MP3 player, tangled earphones, sticker sheets, printed photo strips, a plaid blanket, and textbooks. The room has a low bed, a simple wood desk, a corkboard with blurred photos, pastel curtains, and warm desk-lamp light. The image should feel like a soft early-digital-camera snapshot from around 2011: mild grain, low dynamic range, gentle flash falloff, slightly awkward framing, and cozy clutter. Add a few decorative sticker-like shapes as physical objects on the desk, not digital overlays, and keep all writing unreadable. Avoid real social media logos, readable text, existing webtoon characters, celebrity likeness, childish sexualization, anime style, distorted hands, extra fingers, watermark, and modern smartphone design.', 'mixed'::public.prompt_language, 36),
    ('8d8202b5-c447-4d02-8853-0ff445ec95df'::uuid, 'e70dc327-d49f-433f-8069-0394dd6b3d4e'::uuid, '10000000-0000-4000-8000-000000000001'::uuid, '첫사랑 네컷 사진 스트립', '인스타 프롬프트 카드에서 자주 보이는 폴라로이드/포토부스 감성을 한국 청춘물로 변형.', '사진/시네마틱', 'GPT Image 2.0', '4:5', 'Photo Booth Memory', '/samples/instagram-polaroid-first-love-strip.png', array['인스타트렌드', '네컷사진', '첫사랑', '폴라로이드']::text[], 'Create a vertical 4:5 photorealistic Korean photo-booth memory image from this exact detailed prompt: A strip of four old photo-booth pictures lies on a cafe table beside a half-finished iced drink and a cheap mechanical pencil. Each small photo shows two anonymous young adult school friends in a 2010s Korean first-love youth-drama mood, making slightly different awkward poses: looking away, laughing, holding up a small hand heart, and standing stiffly side by side. The photo strip should look physically printed, slightly glossy, with soft flash, gentle overexposure, dust specks, and no readable text or brand mark. The background table includes a folded school timetable with all writing blurred, a coin purse, and an old feature phone, creating a nostalgic 2012 atmosphere. Use macro focus on the printed strip, shallow depth of field, warm cafe light, natural paper texture, and muted pastel colors. Avoid identifiable faces, existing webtoon characters, readable text, logos, celebrity likeness, kissing, sexualized poses, extra fingers, watermark, and modern smartphone props.', 'mixed'::public.prompt_language, 37),
    ('7f9bdcbf-c698-4b83-8a49-398687501fb6'::uuid, 'f2a96ef3-bb3d-4554-8372-1db7ac3ff0c2'::uuid, '10000000-0000-4000-8000-000000000002'::uuid, 'GPT Image 액션 피규어 패키지 프롬프트', '투명 블리스터 팩, 카드백, 소품 칸, 이름표까지 갖춘 인스타/틱톡용 AI 액션 피규어 패키지 프롬프트.', '제품/광고', 'GPT Image 2.0', '4:5', 'GPT Image Action Figure Package', '/samples/instagram-action-figure-package.png', array['GPT Image', '액션피규어', '피규어패키지', '블리스터팩', '인스타트렌드']::text[], 'Create a vertical 4:5 premium product photograph for GPT Image using this exact detailed prompt:

Turn the uploaded reference person, original character, or described persona into a high-end collectible action figure sealed inside realistic retail blister packaging. If no reference photo is provided, create an anonymous stylish AI prompt creator character instead: black oversized hoodie, loose black cargo pants, black-and-white sneakers, small crossbody camera bag, soft layered black hair, calm downward gaze, one hand holding a miniature camera and the other holding a tiny prompt notebook.

Packaging structure: a clear molded PET plastic blister with believable rounded edges, subtle thickness, tiny seams, soft dents, and realistic specular highlights; a thick matte cardboard backing card with a die-cut hang tab at the top; separate molded accessory compartments on the right side; a larger figure compartment on the left; a small bottom nameplate area with either the simple label "PROMPT MAKER" or abstract unreadable display marks if text rendering is unstable. The packaging should feel like a real premium collectible sold in a design-store toy aisle, not a flat poster.

Figure design: the figure should look like a physical 1/12 scale articulated collectible, with subtle joint lines at shoulders, elbows, wrists, knees, and ankles, but still elegant and not mechanical. Use realistic vinyl/plastic skin material, matte fabric-like sculpting on the hoodie, layered folds in the cargo pants, tiny zipper pulls, shoe stitching, bag buckles, and small painted details. The pose should be relaxed and slightly asymmetrical, with believable toy balance inside the blister tray.

Accessories: arrange each accessory in its own clear compartment with clean spacing: a miniature laptop showing an abstract prompt interface with no readable words, over-ear headphones, a tiny takeaway coffee cup with no logo, a small blank image card, a sheet of abstract stickers, a compact camera lens, a black notebook, and a pen. The accessories must look like miniature plastic objects, not full-size objects pasted into the scene.

Graphic design: use an original packaging card design with cream paper texture, black brush-like marks, muted violet blocks, small lime-yellow accent shapes, tiny abstract UI symbols, and decorative microtext that is intentionally unreadable. Do not use any real brand name, toy franchise layout, social media logo, barcode numbers, QR code, or copyrighted character reference. The overall look should be trendy enough for an Instagram AI prompt post but clean enough for a product catalog.

Lighting and camera: shoot it as a realistic studio product photo, straight-on with a slight 70mm lens compression, softbox reflection across the curved plastic, controlled shadow beneath the package, gentle gray background, crisp focus on the figure and accessories, subtle depth from the blister plastic, realistic cardboard fibers, dust-free but tactile materials, and high dynamic range without looking CGI.

Quality controls: keep the full package visible in frame, preserve the rectangular card silhouette, avoid cutting off the hang tab or bottom edge, keep hands and accessories anatomically clean, keep all text either exactly requested or unreadable, and make the image feel like a real photographed object.

Negative instructions: no Barbie, no Funko, no Marvel, no DC, no anime franchise, no celebrity likeness, no readable brand logos, no watermark, no messy random letters, no deformed hands, no extra fingers, no duplicate heads, no melted plastic, no floating accessories, no warped packaging, no flat 2D illustration, no low-resolution screenshot, no over-saturated toy colors.', 'mixed'::public.prompt_language, 38),
    ('8486a4d7-fa28-4b27-8ab2-82f4fc6904d0'::uuid, '702a22c2-93cd-4c46-8a2f-d48435938b34'::uuid, '10000000-0000-4000-8000-000000000001'::uuid, 'Quiet Luxury 패션 변환컷', 'Gemini/Nano Banana 계열 패션 변환 프롬프트 흐름을 로고 없는 룩북 이미지로 정리.', '인물/패션', 'GPT Image 2.0', '4:5', 'AI Fashion Transformation', '/samples/instagram-gemini-fashion-tryon.png', array['인스타트렌드', '패션', 'Gemini', 'NanoBanana']::text[], 'Create a vertical 4:5 fashion transformation image from this exact detailed prompt: An Instagram-style AI fashion prompt result showing one anonymous adult model in a clean studio wearing a complete quiet-luxury outfit generated as if from a text prompt, not copied from any brand. The model stands in a relaxed full-body pose against a warm off-white seamless background. Outfit: oversized slate-gray wool blazer, white ribbed tank top, wide black pleated trousers, minimal leather loafers, thin silver necklace, and a structured dark brown shoulder bag with no logo. Lighting: large softbox from the left, gentle shadow on the floor, realistic fabric texture, natural skin, and editorial catalog polish. Add subtle visual hints of an AI style-transfer prompt trend through floating translucent fabric swatches and small abstract prompt-card shapes in the background, but no readable words. Composition should be clean and useful for a fashion inspiration post. Avoid brand logos, readable text, celebrity likeness, unrealistic body proportions, extra limbs, plastic skin, overdone makeup, duplicated hands, watermark, and runway background.', 'mixed'::public.prompt_language, 39),
    ('48323d49-f66a-4e1b-8579-3c0d6d7d42d1'::uuid, 'f3521e9b-5eda-4aec-8b04-ddf31b5c11b5'::uuid, '10000000-0000-4000-8000-000000000003'::uuid, '나노바나나 스티커팩 편집', '인스타에서 강한 Nano Banana/AI 편집 프롬프트 흐름을 오리지널 캐릭터 스티커팩으로 변형.', '캐릭터/웹툰', 'GPT Image 2.0', '1:1', 'AI Sticker Pack Edit', '/samples/instagram-nano-banana-stickers.png', array['인스타트렌드', '스티커', 'NanoBanana', '캐릭터']::text[], 'Create a square 1:1 playful AI sticker-edit result from this exact detailed prompt: A cute original character sticker pack laid out on a clean white desk, inspired by viral Instagram AI image editing prompts and Nano Banana / Gemini prompt transformation culture, but not using any real mascot. The main subject is one original rounded yellow fruit-like character with tiny arms, big expressive eyes, and a small green leaf hat, repeated as six separate physical vinyl stickers: happy pose, sleepy pose, surprised pose, holding a tiny camera, wearing headphones, and waving. The stickers have glossy laminated edges, soft shadows, and a few peeled corners to show they are physical objects. Around them are a blank prompt card, a tablet edge, washi tape, and a small cutting mat with no readable text. Style should be clean, cheerful, social-media-friendly, and useful as a prompt result preview. Avoid real brand names, readable words, copyrighted mascots, Minion-like design, Pikachu-like design, logos, watermark, distorted character faces, clutter, and digital UI screenshots.', 'mixed'::public.prompt_language, 40),
    ('192f52f4-4575-4dbd-8b14-cb963654f64b'::uuid, '2a46312e-c15e-44c5-8f9c-6ba6d96bfe42'::uuid, '10000000-0000-4000-8000-000000000005'::uuid, '인스타 프롬프트 카드 콜라주', '이미지 안에 프롬프트 텍스트가 함께 들어가는 인스타 캐러셀 포맷을 저작권 안전하게 재구성.', '편집/콜라주', 'GPT Image 2.0', '4:5', 'Prompt Card Collage', '/samples/instagram-prompt-card-collage.png', array['인스타트렌드', '프롬프트카드', '콜라주', '캐러셀']::text[], 'Create a vertical 4:5 social media prompt-card collage image from this exact detailed prompt: A polished Instagram-style AI prompt carousel cover shown as a physical design board on a desk, not a screenshot. The board contains one large generated-looking cinematic image area at the top showing an anonymous person standing in rain under neon lights, and below it several neat prompt blocks represented only by abstract blurred lines, colored labels, and unreadable microtext. Add small visual elements: paper clips, translucent sticky tabs, a pencil, a tiny camera memory card, and a soft shadow from window light. The design should communicate ''image + prompt text'' clearly without including any readable prompt words. Use a clean editorial layout, off-white paper texture, black typography-like marks that are illegible, cyan and warm orange accent stickers, and realistic overhead photography. This should feel like the kind of prompt-sharing image people post on Instagram, but original and copyright-safe. Avoid readable text, real usernames, Instagram UI, logos, brand marks, QR codes, watermark, messy layout, random letters, distorted photo area, and low-quality screenshot styling.', 'mixed'::public.prompt_language, 41),
    ('fbe20e3c-b286-46c9-8838-10291fc84168'::uuid, 'e4def8b9-ea1b-4328-8864-ae685453c988'::uuid, '10000000-0000-4000-8000-000000000001'::uuid, '거울 속 실내 수영장 셀피', '간단한 한 줄 아이디어가 강하게 먹히는 인스타식 초현실 AI 사진 프롬프트.', '사진/시네마틱', 'GPT Image 2.0', '4:5', 'Surreal Mirror Selfie', '/samples/instagram-surreal-mirror-selfie.png', array['인스타트렌드', '거울셀피', '초현실', '디카']::text[], 'Create a vertical 4:5 surreal but photorealistic mirror selfie concept from this exact detailed prompt: An anonymous adult stands in a quiet apartment hallway taking a mirror selfie with an old compact digital camera, but the mirror reflection shows a different impossible room behind them: a sunlit indoor swimming pool with blue tiles and floating curtains. The real hallway is dim, beige, and ordinary, with shoes by the door, a coat rack, and soft evening light; the reflected pool room is bright, dreamy, and slightly uncanny. The subject''s face should be obscured by the compact camera and not identifiable. Use realistic mirror reflections, subtle dust on the mirror, 2000s digital camera flash, muted colors, mild grain, and a clean vertical composition suited to an Instagram AI photo prompt. The image should feel like an impossible edit that could become viral because the prompt idea is simple and striking. Avoid readable text, logos, smartphone UI, celebrity likeness, horror monsters, gore, warped hands, extra limbs, impossible mirror frame geometry, watermark, and cartoon styling.', 'mixed'::public.prompt_language, 42),
    ('e0a647de-e79e-473f-83ae-60ccd9a68cd1'::uuid, '4500c5c2-9287-4d67-8d17-afb91e79fa55'::uuid, '10000000-0000-4000-8000-000000000003'::uuid, '2013년 골목길 첫사랑 무드', '좁은 주택가, 편의점 불빛, 물웅덩이 반사로 만든 한국 청춘 웹툰 실사화 스틸.', '사진/시네마틱', 'GPT Image 2.0', '16:9', '2013 Korean Night Walk', '/samples/instagram-webtoon-night-walk.png', array['인스타트렌드', '웹툰실사화', '2013', '청춘영화']::text[], 'Create a horizontal 16:9 cinematic lifestyle photo from this exact detailed prompt: A nostalgic Korean night walk scene that feels like a live-action version of a 2010s school romance webtoon, but completely original. Two anonymous young adult actors in casual school-uniform-inspired outfits walk separately on opposite sides of a narrow residential street, both pretending not to notice each other. Between them are wet asphalt reflections, old streetlights, a small convenience store glow in the distance, parked compact cars with unreadable plates, and apartment windows with warm light. The camera is placed low behind a puddle so their reflections appear near the bottom of the frame. Use realistic 35mm lens compression, soft mist, muted blue-orange color grade, natural awkward body language, and a quiet emotional tone. It should look like a still from a Korean youth film made around 2013, not a modern glossy drama. Avoid existing webtoon references, readable signs, logos, celebrity likeness, kissing, sexualized poses, extra fingers, warped legs, watermark, anime style, and excessive rain effects.', 'mixed'::public.prompt_language, 43)
), upserted_posts as (
  insert into public.image_posts (
    id, author_id, title, description, category, model, aspect_ratio, style, image_url, image_urls, tags, is_hidden, created_at, updated_at
  )
  select
    id, author_id, title, description, category, model, aspect_ratio, style, image_url, array[image_url]::text[], tags, false,
    now() - (offset_hours || ' hours')::interval,
    now()
  from seed_posts
  on conflict (id) do update
  set
    author_id = excluded.author_id,
    title = excluded.title,
    description = excluded.description,
    category = excluded.category,
    model = excluded.model,
    aspect_ratio = excluded.aspect_ratio,
    style = excluded.style,
    image_url = excluded.image_url,
    image_urls = excluded.image_urls,
    tags = excluded.tags,
    is_hidden = false,
    updated_at = now()
  returning id
)
insert into public.prompt_versions (id, image_post_id, label, language, body)
select version_id, id, '실제 프롬프트', prompt_language, prompt_body
from seed_posts
on conflict (id) do update
set
  label = excluded.label,
  language = excluded.language,
  body = excluded.body;

create trigger image_posts_authenticated_rate_limit
before insert on public.image_posts
for each row execute function public.enforce_authenticated_write_rate_limit_trigger('image_post');

notify pgrst, 'reload schema';
